### PR TITLE
Issue 306: Developed Response Action RA2117: Analyse user-agent

### PR DESCRIPTION
**Pull request by pjabes**
As outlined within https://github.com/atc-project/atc-react/issues/306.

### CODE REVIEW

**Comment by yugoslavskiy** [comment]
Hello @pjabes! I am not sure if you've seen my https://github.com/atc-project/atc-react/issues/306#issuecomment-757216187 regarding your PR. Would you like to proceed with the adjustments or we should do it ourselves?

**Comment by pjabes** [comment]
Hello @yugoslavskiy.  Will proceed with the adjustments!  Have been sidetracked the last few months - should have something shortly for you.

**Comment by pjabes** [comment]
Hi @yugoslavskiy,

Completed and ready for your review.

Changes:
* Formatted markdown into the standard spec.
* Minor content and formatting changes to be more in-line with the spirit of the project (for instance, "Important Notes" to "Important Considerations"). 

I've attached a locally generated instance as testing proof.

image

**Comment by yugoslavskiy** [comment]
It looks gorgeous! Thank you very much for your contribution, @pjabes!

**Pull request merged**
