### PR TITLE
Add various response actions for identification stage

### PR DESCRIPTION
**Pull request by Karneades**
This RA's for identifications were added
* User agent search
* Referrer search
* Email attributes search
* List process injections
* List local accounts
* List user logins on remote systems

I was wondering in which category one would put "context analysis" or "OSINT" actions, e.g. look for leaked credentials in Github, pastebin, ... as an action after a compromised account.

Maybe I should wait adding more actions until the numbering and the fields are clear for the files. What do you think? For me I would prefer only using names inside the action files instead of numbers for stage and category. Both are directly visible on the matrix when looking up existing actions.

### CODE REVIEW

**Comment by yugoslavskiy** [comment]
Hello @Karneades ! Thank you for your contribution. Right now we have an extremely busy schedule, no option to process your PR. We will respond to it during the week for sure.

**Comment by yugoslavskiy** [comment]
Hello @Karneades !

> I was wondering in which category one would put "context analysis" or "OSINT" actions, e.g. look for leaked credentials in Github, pastebin, ... as an action after a compromised account.

I would say that this sort of actions supposed to be done by the Threat Detection process. Here is a [discussion regarding the split](https://github.com/atc-project/atc-react/issues/291) between RE&CT and TD (I've already mentioned it in the second PR of yours).

Please join it so we could discuss it and define the way we will move forward with such lookups.

Regarding your contribution — everything could be added right now.
I would only doubt `List process injections`. It is a good point for discussion that I've mentioned above.

**Comment by Karneades** [comment]
Will close the PR as I'm unsure what the result of the IR/TD discussion is. Maybe I can work on that actions at a later point again.

**Comment by yugoslavskiy** [comment]
Hello @Karneades!

> I'm unsure what the result of the IR/TD discussion is.

I believe that it makes sense to **participate** in the discussion to clear that out. 

It is open and you are welcome to join.

Thanks!

**Pull request closed without merging**
